export const exportToPDF = (title: string, htmlContent: string) => {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export PDF");
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Arial, sans-serif; padding: 24px; color: #1a1a1a; }
        .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #2563eb; padding-bottom: 16px; }
        .header h1 { font-size: 20px; font-weight: 700; color: #1e293b; }
        .header p { font-size: 12px; color: #64748b; margin-top: 4px; }
        .section-title { font-size: 14px; font-weight: 700; margin: 16px 0 8px; color: #334155; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 12px; }
        th { background: #f1f5f9; text-align: left; padding: 8px 10px; font-weight: 600; border: 1px solid #e2e8f0; }
        td { padding: 8px 10px; border: 1px solid #e2e8f0; }
        tr:nth-child(even) { background: #f8fafc; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 10px; font-weight: 600; }
        .badge-red { background: #fee2e2; color: #dc2626; }
        .badge-yellow { background: #fef9c3; color: #ca8a04; }
        .badge-green { background: #dcfce7; color: #16a34a; }
        .footer { margin-top: 32px; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
        .alert { background: #fee2e2; border: 1px solid #fca5a5; border-radius: 8px; padding: 8px 12px; margin-bottom: 8px; font-size: 12px; color: #b91c1c; }
        @media print { body { padding: 12px; } }
      </style>
    </head>
    <body>
      ${htmlContent}
      <div class="footer">Generated by AnganTrack · ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })} · ${new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}</div>
    </body>
    </html>
  `);
  printWindow.document.close();
  setTimeout(() => printWindow.print(), 300);
};
